Log file created at: 2016/10/26 10:01:34
Running on machine: PC-20160710NSGJ
Binary: Built with gc go1.7beta1 for windows/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1026 10:01:34.938930    9928 main.go:96] -----------------ServerINIT------------------------
I1026 10:01:34.963932    9928 main.go:97] -----------------zhengshi db------------------------
I1026 10:01:34.963932    9928 main.go:102] -----------------ServerINIT------------------------
I1026 10:01:34.963932    9928 main.go:104] =====================ResPath:120.25.83.66/res/
I1026 10:01:34.963932    9928 redis_writedata.go:668] Entry Redis_Write_Player_PaiHangData!!!
I1026 10:01:34.964932    9928 InItLoginData.go:30] -------------ZiGameConnetHallServer---------------
I1026 10:01:34.964932    9928 InItLoginData.go:61] ws://run.websocket.club:7001/RuiLiDe?data={"Protocol":3,"Protocol2":1,"OpenID":"33f1efc5d57b60ec65a4a382e13bb891"}
I1026 10:01:35.182944    9928 InItLoginData.go:90] SendHallServerDataFun:{8 1 33f1efc5d57b60ec65a4a382e13bb891}
I1026 10:01:35.183944    9928 InItLoginData.go:119] Enrty ReceiveHallServerDataFun
I1026 10:01:36.136999    9928 redis_pool.go:44] error on connect redis serverSYSTEM_ERROR - NewSyncConnection [cause: newConnHdl(): could not open connection]
I1026 10:01:37.322066    9928 redis_pool.go:44] error on connect redis serverSYSTEM_ERROR - NewSyncConnection [cause: newConnHdl(): could not open connection]
I1026 10:01:38.465132    9928 redis_pool.go:44] error on connect redis serverSYSTEM_ERROR - NewSyncConnection [cause: newConnHdl(): could not open connection]
I1026 10:01:39.627198    9928 redis_pool.go:44] error on connect redis serverSYSTEM_ERROR - NewSyncConnection [cause: newConnHdl(): could not open connection]
I1026 10:01:40.766263    9928 redis_pool.go:44] error on connect redis serverSYSTEM_ERROR - NewSyncConnection [cause: newConnHdl(): could not open connection]
I1026 10:01:41.924330    9928 redis_pool.go:44] error on connect redis serverSYSTEM_ERROR - NewSyncConnection [cause: newConnHdl(): could not open connection]
I1026 10:01:43.049394    9928 redis_pool.go:44] error on connect redis serverSYSTEM_ERROR - NewSyncConnection [cause: newConnHdl(): could not open connection]
I1026 10:01:44.207460    9928 redis_pool.go:44] error on connect redis serverSYSTEM_ERROR - NewSyncConnection [cause: newConnHdl(): could not open connection]
I1026 10:01:45.356526    9928 redis_pool.go:44] error on connect redis serverSYSTEM_ERROR - NewSyncConnection [cause: newConnHdl(): could not open connection]
I1026 10:01:46.485591    9928 redis_pool.go:44] error on connect redis serverSYSTEM_ERROR - NewSyncConnection [cause: newConnHdl(): could not open connection]
I1026 10:01:47.667658    9928 redis_pool.go:44] error on connect redis serverSYSTEM_ERROR - NewSyncConnection [cause: newConnHdl(): could not open connection]
I1026 10:01:48.808723    9928 redis_pool.go:44] error on connect redis serverSYSTEM_ERROR - NewSyncConnection [cause: newConnHdl(): could not open connection]
I1026 10:01:49.942788    9928 redis_pool.go:44] error on connect redis serverSYSTEM_ERROR - NewSyncConnection [cause: newConnHdl(): could not open connection]
I1026 10:01:51.094854    9928 redis_pool.go:44] error on connect redis serverSYSTEM_ERROR - NewSyncConnection [cause: newConnHdl(): could not open connection]
I1026 10:01:52.254921    9928 redis_pool.go:44] error on connect redis serverSYSTEM_ERROR - NewSyncConnection [cause: newConnHdl(): could not open connection]
I1026 10:01:53.412987    9928 redis_pool.go:44] error on connect redis serverSYSTEM_ERROR - NewSyncConnection [cause: newConnHdl(): could not open connection]
I1026 10:01:54.556052    9928 redis_pool.go:44] error on connect redis serverSYSTEM_ERROR - NewSyncConnection [cause: newConnHdl(): could not open connection]
I1026 10:01:55.685117    9928 redis_pool.go:44] error on connect redis serverSYSTEM_ERROR - NewSyncConnection [cause: newConnHdl(): could not open connection]
I1026 10:01:56.897186    9928 redis_pool.go:44] error on connect redis serverSYSTEM_ERROR - NewSyncConnection [cause: newConnHdl(): could not open connection]
I1026 10:01:58.049252    9928 redis_pool.go:44] error on connect redis serverSYSTEM_ERROR - NewSyncConnection [cause: newConnHdl(): could not open connection]
I1026 10:01:59.188317    9928 redis_pool.go:44] error on connect redis serverSYSTEM_ERROR - NewSyncConnection [cause: newConnHdl(): could not open connection]
I1026 10:02:00.345383    9928 redis_pool.go:44] error on connect redis serverSYSTEM_ERROR - NewSyncConnection [cause: newConnHdl(): could not open connection]
I1026 10:02:01.521451    9928 redis_pool.go:44] error on connect redis serverSYSTEM_ERROR - NewSyncConnection [cause: newConnHdl(): could not open connection]
I1026 10:02:02.657516    9928 redis_pool.go:44] error on connect redis serverSYSTEM_ERROR - NewSyncConnection [cause: newConnHdl(): could not open connection]
I1026 10:02:03.795581    9928 redis_pool.go:44] error on connect redis serverSYSTEM_ERROR - NewSyncConnection [cause: newConnHdl(): could not open connection]
